### ISSUE TITLE
Encryption does not work for UTF-8 Strings.

### ISSUE THREAD

**Issue by Seelengrab** [kanav99/AES.jl#11]
Julia Strings are by default UTF-8 encoded and thus can't simply be used like arrays of UInt8. The code currently assumes that any character in a given String can be converted to UInt8 without a problem, but this doesn't work:

```
julia> str = "UTF-8! 😉"
"UTF-8! 😉"

julia> cipher = AESCipher();

julia> encrypt(str, cipher)
ERROR: InexactError: trunc(UInt8, 128521)
 [...]
```

I've forked this project and I'm trying to fix this properly, but that has exposed some other problems as well - I'll try to make a PR if I get this and the other problems exposed by this fixed.

**Comment by kanav99** [comment]
Sorry about that and thank you so much! The package needs a lot of development right now, but I just don't get time these days for active fixes. Do tell me if you need help in getting the PR done!
